name: zine
description: Application Zine

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  provider: ^4.0.5

  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo_zine.png
    - assets/john_doe.png
    - assets/icons/cross.png
    - assets/icons/design.png
    - assets/icons/logout.png
    - assets/icons/notification.png
    - assets/icons/user.png

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-400.ttf
        - asset: assets/fonts/ProductSans-700.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-400-italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans-700-italic.ttf
          weight: 700
          style: italic
